### ISSUE TITLE
Rüstung mit Variablen Preis noch nicht eingetragen.

### ISSUE THREAD

**Issue by LBCrusher** [DSA-H/dsa-h#13]

**Comment by Jotschi89** [comment]
Versteh ich nicht. Erklärung?

**Comment by LBCrusher** [comment]
Das hab ich mir eingetragen nur dfür die datenbank

Am 29. Januar 2015 um 17:23 schrieb Jotschi89 notifications@github.com:

**Comment by Jotschi89** [comment]
OK, hab dafür mal ein label angelegt.
