### ISSUE TITLE
Kategorienupdate Gegenstanderstellung

### ISSUE THREAD

**Issue by LBCrusher** [DSA-H/dsa-h#14]
Wenn man einen Gegenstand erstellt/bearbeitet und eine seiner Kategorien löscht kann man sie nicht gleich wieder hinzufügen, da sie in der Auswahl dann fehlt (bei neuladen wieder vorhanden)

**Comment by Jotschi89** [comment]
Stimmt so nicht. Man kann sie wieder hinzufügen, allerdings ist die Kategorie nicht richtig einsortiert, sondern einfach ganz unten.

**Comment by Jotschi89** [comment]
Das Problem tritt generell bei allen Dropdownlisten auf, aus denen entfernt hinzugefügt werden kann
