### ISSUE TITLE
Datum setzen

### ISSUE THREAD

**Issue by LBCrusher** [DSA-H/dsa-h#16]
Wenn man ein Datum setzt muss man zuerst nächster Tag drücken bis es wirklich dorthingesetzt wird. Wäre toll wenn das ohne den Tag vorstellen button geht

**Comment by Jotschi89** [comment]
Das ist ein Anzeige Fehler - die mainview wird nicht geupdatet nach dem ändern. Man muss nicht nächster Tag klicken, es reicht auch, wenn man irgenetwas anderes macht, das die Anzeige updated. Sollte leicht zu fixen sein
